### ISSUE TITLE
Item duplication on 2.2.0

### ISSUE THREAD

**Issue by OttoWerse** [zerofall/EZStorage2#32]
ON Version 2.2.0, when you set the extraction port to extract an item, it will extract said item an infinite amount of times, without updating the number of items in the stack. Therefore if you have, for example 1 iron ore in your system, and set the port to extract iron ore into a chest, it will give you infinite iron ore without ever depleting the initial single ore. I haven't seen this issue being marked as fixed in 2.2.1 or 2.2.2 so I think it does still apply to those versions, although I haven't updated to them yet, and can'T confirm that they still apply. 

I use this mod on a modified version of All the Mods, so if it does not occur on vanilla, it might be a compatibility issue with some other mod(s).

**Comment by sblectric** [comment]
Try using 2.2.2 and see if it still happens.

**Comment by sblectric** [comment]
Reopen this issue if it does, it should be fixed though.

**Comment by steuff** [comment]
I'm using 2.2.3 (with Forge 12.18.1.2088, Minecraft 1.10.2) and still have this bug.
However, it only occurs when using Mekanism 9.2.0 pipes (Logistical Transporter; all tiers) connected to the Extraction Port.
Using Ender IO pipes (Item Conduit), it seems to work as intended.

Modpack: Avant 3.

**Comment by sblectric** [comment]
Hmm, strange. Will look into this.

**Comment by tomaste** [comment]
using version 2.2.6, and this issue is still happening.  
Added 1 dirt, and an export port.
Put a translocator on the export port into a vanilla chest, and unlimited dirt flows out.

**Comment by sblectric** [comment]
@tomaste Does the dirt decrease in the system at all, or does it get depleted without going down?

**Comment by tomaste** [comment]
it does not decrease.  I just put one dirt in, and hey unlimited dirt out.

**Comment by Rensik** [comment]
Item Duplication in 2.2.6

https://gyazo.com/db8f49075fcfe7159873006d7c9ba43d

**Comment by sblectric** [comment]
Fix planned for 2.3.0

**Comment by sblectric** [comment]
Fixed in 2.3.0.
